/*******************************************************************
  This file has been automatically generated by ispc
  DO NOT EDIT THIS FILE DIRECTLY
 *******************************************************************/

/* Provide Declarations */
#include <stdarg.h>
#include <setjmp.h>
#include <limits.h>
#include <stdlib.h>
#ifdef _MSC_VER
  #define NOMINMAX
  #include <windows.h>
#endif // _MSC_VER
#include <stdlib.h>
#include <stdint.h>
/* get a declaration for alloca */
#ifdef _MSC_VER
  #include <malloc.h>
  #define alloca _alloca
#else
  #include <alloca.h>
#endif

#undef ISPC_FAST_MATH
#include "knc.h"

/* Basic Library Function Declarations */
extern "C" {
int puts(unsigned char *);
unsigned int putchar(unsigned int);
int fflush(void *);
int printf(const unsigned char *, ...);
uint8_t *memcpy(uint8_t *, uint8_t *, uint64_t );
uint8_t *memset(uint8_t *, uint8_t, uint64_t );
void memset_pattern16(void *, const void *, uint64_t );
}

#ifndef __GNUC__  /* Can only support "linkonce" vars with GCC */
#define __attribute__(X)
#endif

#if defined(__GNUC__) && defined(__APPLE_CC__)
#define __EXTERNAL_WEAK__ __attribute__((weak_import))
#elif defined(__GNUC__)
#define __EXTERNAL_WEAK__ __attribute__((weak))
#else
#define __EXTERNAL_WEAK__
#endif

#if defined(__GNUC__) && defined(__APPLE_CC__)
#define __ATTRIBUTE_WEAK__
#elif defined(__GNUC__)
#define __ATTRIBUTE_WEAK__ __attribute__((weak))
#else
#define __ATTRIBUTE_WEAK__
#endif

#if defined(__GNUC__)
#define __HIDDEN__ __attribute__((visibility("hidden")))
#endif

#if (defined(__GNUC__) || defined(__clang__)) && !defined(__INTEL_COMPILER)
#define LLVM_NAN(NanStr)   __builtin_nan(NanStr)   /* Double */
#define LLVM_NANF(NanStr)  __builtin_nanf(NanStr)  /* Float */
#define LLVM_NANS(NanStr)  __builtin_nans(NanStr)  /* Double */
#define LLVM_NANSF(NanStr) __builtin_nansf(NanStr) /* Float */
#define LLVM_INF           __builtin_inf()         /* Double */
#define LLVM_INFF          __builtin_inff()        /* Float */
//#define LLVM_PREFETCH(addr,rw,locality) __builtin_prefetch(addr,rw,locality)
//#define __ATTRIBUTE_CTOR__ __attribute__((constructor))
//#define __ATTRIBUTE_DTOR__ __attribute__((destructor))
#elif defined(_MSC_VER) || defined(__INTEL_COMPILER)
#include <limits>
#define LLVM_NAN(NanStr)   std::numeric_limits<double>::quiet_NaN()
#define LLVM_NANF(NanStr)  std::numeric_limits<float>::quiet_NaN()
#define LLVM_NANS(NanStr)  std::numeric_limits<double>::signaling_NaN()
#define LLVM_NANSF(NanStr) std::numeric_limits<float>::signaling_NaN()
#define LLVM_INF           std::numeric_limits<double>::infinity()
#define LLVM_INFF          std::numeric_limits<float>::infinity()
//#define LLVM_PREFETCH(addr,rw,locality)            /* PREFETCH */
//#define __ATTRIBUTE_CTOR__
//#define __ATTRIBUTE_DTOR__
#else
#error "Not MSVC, clang, or g++?"
#endif

#if (defined(__GNUC__) || defined(__clang__))
#define LLVM_ASM(X) __asm(X)
#endif

#if defined(__clang__) || defined(__INTEL_COMPILER) || (__GNUC__ < 4) /* Old GCCs, or compilers not GCC */ 
#define __builtin_stack_save() 0   /* not implemented */
#define __builtin_stack_restore(X) /* noop */
#endif

#define CODE_FOR_MAIN() /* Any target-specific code for main()*/

#ifndef __cplusplus
typedef unsigned char bool;
#endif


/* Support for floating point constants */
typedef uint64_t ConstantDoubleTy;
typedef uint32_t ConstantFloatTy;
typedef struct { unsigned long long f1; unsigned short f2; unsigned short pad[3]; } ConstantFP80Ty;
typedef struct { uint64_t f1, f2; } ConstantFP128Ty;


/* Global Declarations */


/* Helper union for bitcasts */
typedef union {
  unsigned int Int32;
  unsigned long long Int64;
  float Float;
  double Double;
} llvmBitCastUnion;
/* Structure and array forward declarations */
struct l_unnamed_0;

/* Structure and array contents */
struct l_unnamed_0 {
  static l_unnamed_0 init(uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3, uint32_t v4, uint32_t v5, uint32_t v6, uint32_t v7, float *v8, float *v9, float *v10, float *v11, __vec16_i1 v12) {
    l_unnamed_0 ret;
    ret.field0 = v0;
    ret.field1 = v1;
    ret.field2 = v2;
    ret.field3 = v3;
    ret.field4 = v4;
    ret.field5 = v5;
    ret.field6 = v6;
    ret.field7 = v7;
    ret.field8 = v8;
    ret.field9 = v9;
    ret.field10 = v10;
    ret.field11 = v11;
    ret.field12 = v12;
    return ret;
  }
  uint32_t field0;
  uint32_t field1;
  uint32_t field2;
  uint32_t field3;
  uint32_t field4;
  uint32_t field5;
  uint32_t field6;
  uint32_t field7;
  float *field8;
  float *field9;
  float *field10;
  float *field11;
  __vec16_i1 field12;
};



/* Function Declarations */
extern "C" {
uint8_t *ISPCAlloc(uint8_t **, uint64_t , uint32_t );
void ISPCLaunch(uint8_t **, uint8_t *, uint8_t *, uint32_t );
void ISPCSync(uint8_t *);
static void stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, float *coef_, float *vsq_, float *Ain_, float *Aout_);
static void stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(l_unnamed_0 *, uint32_t , uint32_t , uint32_t , uint32_t );
void loop_stencil_ispc_tasks___uniuniuniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_un_3C_unf_3E_(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_, __vec16_i1 __mask_);
void loop_stencil_ispc___uniuniuniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_un_3C_unf_3E_(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_, __vec16_i1 __mask_);
void loop_stencil_ispc_tasks(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_);
void loop_stencil_ispc(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_);
}



/* Function Bodies */
template <typename A, typename B> static inline int llvm_fcmp_ord(A X, B Y) { return X == X && Y == Y; }
template <typename A, typename B> static inline int llvm_fcmp_uno(A X, B Y) { return X != X || Y != Y; }
template <typename A, typename B> static inline int llvm_fcmp_ueq(A X, B Y) { return X == Y || llvm_fcmp_uno(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_une(A X, B Y) { return X != Y; }
template <typename A, typename B> static inline int llvm_fcmp_ult(A X, B Y) { return X <  Y || llvm_fcmp_uno(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_ugt(A X, B Y) { return X >  Y || llvm_fcmp_uno(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_ule(A X, B Y) { return X <= Y || llvm_fcmp_uno(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_uge(A X, B Y) { return X >= Y || llvm_fcmp_uno(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_oeq(A X, B Y) { return X == Y ; }
template <typename A, typename B> static inline int llvm_fcmp_one(A X, B Y) { return X != Y && llvm_fcmp_ord(X, Y); }
template <typename A, typename B> static inline int llvm_fcmp_olt(A X, B Y) { return X <  Y ; }
template <typename A, typename B> static inline int llvm_fcmp_ogt(A X, B Y) { return X >  Y ; }
template <typename A, typename B> static inline int llvm_fcmp_ole(A X, B Y) { return X <= Y ; }
template <typename A, typename B> static inline int llvm_fcmp_oge(A X, B Y) { return X >= Y ; }
template <typename A> A *Memset(A *ptr, int count, size_t len) { return (A *)memset(ptr, count, len); }

static const int32_t __attribute__ ((aligned(64))) VectorConstant0[] = { 0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u, 8u, 9u, 10u, 11u, 12u, 13u, 14u, 15u,  };
static const int32_t __attribute__ ((aligned(64))) VectorConstant1[] = { 0u, 1u, 2u, 3u, 4u, 5u, 6u, 7u, 8u, 9u, 10u, 11u, 12u, 13u, 14u, 15u,  };

static void stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, float *coef_, float *vsq_, float *Ain_, float *Aout_) {
  uint32_t mul_Nx_load_Ny_load_;
  uint32_t aligned_end31_;
  __vec16_i32 x1_smear_;
  uint8_t *Ain_load293_ptr2int_2void_;
  float *coef_load298_offset_;
  float *coef_load349_offset_;
  float *coef_load400_offset_;
  uint8_t *Aout_load466_ptr2int_2void_;
  uint8_t *vsq_load472_ptr2int_2void_;
  uint64_t tmp__1_;
  uint32_t counter_2e_0456_;
  uint32_t counter_2e_0456___PHI;
  uint32_t mul_z_load281_Nxy_load282_broadcast_2e_elt0_;
  uint32_t add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0222_;
  uint32_t add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0232_;
  uint32_t add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0242_;
  uint32_t add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0252_;
  uint32_t tmp440_;
  uint32_t tmp442_;
  uint32_t tmp448_;
  uint32_t tmp450_;
  __vec16_i32 new_counter267_2e_us_smear_;
  __vec16_i1 cmp275_2e_us_;
  uint32_t mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_;
  float coef_load287_offset_load_2e_us_;
  __vec16_f coef_load287_offset_load_2e_us_smear_;
  uint32_t scaled_offsets197_2e_elt0_2e_us_;
  uint64_t tmp__2_;
  uint8_t *ptr199_2e_us_;
  __vec16_f ptr199_masked_load_2e_us_;
  float coef_load298_offset_load_2e_us_;
  __vec16_f coef_load298_offset_load_2e_us_smear_;
  __vec16_f ptr208_masked_load_2e_us_;
  __vec16_f ptr218_masked_load_2e_us_;
  __vec16_f ptr228_masked_load_2e_us_;
  __vec16_f ptr238_masked_load_2e_us_;
  __vec16_f ptr248_masked_load_2e_us_;
  __vec16_f ptr258_masked_load_2e_us_;
  float coef_load349_offset_load_2e_us_;
  __vec16_f coef_load349_offset_load_2e_us_smear_;
  __vec16_f ptr268_masked_load_2e_us_;
  __vec16_f ptr278_masked_load_2e_us_;
  uint32_t add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_;
  __vec16_f ptr288_masked_load_2e_us_;
  __vec16_f ptr298_masked_load_2e_us_;
  uint32_t add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_;
  __vec16_f ptr308_masked_load_2e_us_;
  __vec16_f ptr318_masked_load_2e_us_;
  float coef_load400_offset_load_2e_us_;
  __vec16_f coef_load400_offset_load_2e_us_smear_;
  __vec16_f ptr328_masked_load_2e_us_;
  __vec16_f ptr338_masked_load_2e_us_;
  __vec16_f ptr348_masked_load_2e_us_;
  __vec16_f ptr358_masked_load_2e_us_;
  __vec16_f ptr368_masked_load_2e_us_;
  __vec16_f ptr378_masked_load_2e_us_;
  __vec16_f ptr388_masked_load_2e_us_;
  uint8_t *ptr398_2e_us_;
  __vec16_f ptr398_masked_load_2e_us_;
  __vec16_f ptr408_masked_load_2e_us_;
  uint32_t new_counter35_2e_us_;
  uint32_t counter32_2e_4452_2e_us_;
  uint32_t counter32_2e_4452_2e_us___PHI;
  float coef_load_offset_load_2e_us_;
  __vec16_f coef_load_offset_load_2e_us_smear_;
  uint32_t scaled_offsets_2e_elt0_2e_us_;
  uint64_t tmp__3_;
  __vec16_f (*ptr_cast_for_load_2e_us_);
  __vec16_f ptr_masked_load1_2e_us_;
  float coef_load82_offset_load_2e_us_;
  __vec16_f coef_load82_offset_load_2e_us_smear_;
  __vec16_f ptr7_masked_load9_2e_us_;
  __vec16_f ptr16_masked_load18_2e_us_;
  __vec16_f ptr25_masked_load27_2e_us_;
  __vec16_f ptr34_masked_load36_2e_us_;
  __vec16_f ptr43_masked_load45_2e_us_;
  __vec16_f ptr52_masked_load54_2e_us_;
  float coef_load133_offset_load_2e_us_;
  __vec16_f coef_load133_offset_load_2e_us_smear_;
  __vec16_f ptr61_masked_load63_2e_us_;
  __vec16_f ptr70_masked_load72_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_;
  __vec16_f ptr79_masked_load81_2e_us_;
  __vec16_f ptr88_masked_load90_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_;
  __vec16_f ptr97_masked_load99_2e_us_;
  __vec16_f ptr106_masked_load108_2e_us_;
  float coef_load184_offset_load_2e_us_;
  __vec16_f coef_load184_offset_load_2e_us_smear_;
  __vec16_f ptr115_masked_load117_2e_us_;
  __vec16_f ptr124_masked_load126_2e_us_;
  __vec16_f ptr133_masked_load135_2e_us_;
  __vec16_f ptr142_masked_load144_2e_us_;
  __vec16_f ptr151_masked_load153_2e_us_;
  __vec16_f ptr160_masked_load162_2e_us_;
  __vec16_f ptr169_masked_load171_2e_us_;
  __vec16_f (*ptr_cast_for_load179_2e_us_);
  __vec16_f ptr178_masked_load180_2e_us_;
  __vec16_f ptr187_masked_load189_2e_us_;
  uint32_t new_counter267_2e_us_;
  uint32_t counter25_2e_1454_2e_us_;
  uint32_t counter25_2e_1454_2e_us___PHI;
  uint32_t mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_;
  uint32_t add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt024_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt033_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt042_2e_us_;
  uint32_t add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt051_2e_us_;
  uint32_t tmp420_2e_us_;
  uint32_t tmp422_2e_us_;
  uint32_t tmp428_2e_us_;
  uint32_t tmp430_2e_us_;
  uint32_t new_counter_;
  uint64_t indvars_2e_iv_2e_next_;
  uint64_t indvars_2e_iv_;
  uint64_t indvars_2e_iv___PHI;
  __vec16_i32 x0_smear_;
  __vec16_i1 cmp275_;
  uint32_t tmp__4_;
  uint32_t mul_y_load283_Nx_load284_broadcast_2e_elt0_;
  float coef_load287_offset_load_;
  __vec16_f coef_load287_offset_load_smear_;
  uint32_t scaled_offsets197_2e_elt0_;
  uint64_t tmp__5_;
  uint8_t *ptr199_;
  __vec16_f ptr199_masked_load_;
  float coef_load298_offset_load_;
  __vec16_f coef_load298_offset_load_smear_;
  __vec16_f ptr208_masked_load_;
  __vec16_f ptr218_masked_load_;
  __vec16_f ptr228_masked_load_;
  __vec16_f ptr238_masked_load_;
  __vec16_f ptr248_masked_load_;
  __vec16_f ptr258_masked_load_;
  float coef_load349_offset_load_;
  __vec16_f coef_load349_offset_load_smear_;
  __vec16_f ptr268_masked_load_;
  __vec16_f ptr278_masked_load_;
  uint32_t add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_;
  __vec16_f ptr288_masked_load_;
  __vec16_f ptr298_masked_load_;
  uint32_t add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_;
  __vec16_f ptr308_masked_load_;
  __vec16_f ptr318_masked_load_;
  float coef_load400_offset_load_;
  __vec16_f coef_load400_offset_load_smear_;
  __vec16_f ptr328_masked_load_;
  __vec16_f ptr338_masked_load_;
  __vec16_f ptr348_masked_load_;
  __vec16_f ptr358_masked_load_;
  __vec16_f ptr368_masked_load_;
  __vec16_f ptr378_masked_load_;
  __vec16_f ptr388_masked_load_;
  uint8_t *ptr398_;
  __vec16_f ptr398_masked_load_;
  __vec16_f ptr408_masked_load_;

  mul_Nx_load_Ny_load_ = ((uint32_t )(((uint32_t )Ny_) * ((uint32_t )Nx_)));
  aligned_end31_ = ((uint32_t )(((uint32_t )x1_) - ((uint32_t )(((int32_t )(((int32_t )(((uint32_t )(((uint32_t )x1_) - ((uint32_t )x0_))))) % ((int32_t )16u)))))));
  if ((((int32_t )z0_) < ((int32_t )z1_))) {
    goto foreach_test21_2e_preheader_2e_lr_2e_ph_label;
  } else {
    goto foreach_reset_label;
  }

foreach_test21_2e_preheader_2e_lr_2e_ph_label: {
  x1_smear_ = __smear_i32<__vec16_i32>(x1_);
  Ain_load293_ptr2int_2void_ = ((uint8_t *)Ain_);
  coef_load298_offset_ = (&coef_[((int64_t )1ull)]);
  coef_load349_offset_ = (&coef_[((int64_t )2ull)]);
  coef_load400_offset_ = (&coef_[((int64_t )3ull)]);
  Aout_load466_ptr2int_2void_ = ((uint8_t *)Aout_);
  vsq_load472_ptr2int_2void_ = ((uint8_t *)vsq_);
  tmp__1_ = ((int64_t )(int32_t )y0_);
  counter_2e_0456___PHI = z0_;   /* for PHI node */
  goto foreach_test21_2e_preheader_label;

}
foreach_reset_label: {
  return;
}
  do {     /* Syntactic loop 'foreach_test21.preheader' to make GCC happy */
foreach_test21_2e_preheader_label: {
  counter_2e_0456_ = counter_2e_0456___PHI;
  if ((((int32_t )y0_) < ((int32_t )y1_))) {
    goto outer_not_in_extras_2e_preheader_2e_lr_2e_ph_label;
  } else {
    goto foreach_reset19_label;
  }

}
outer_not_in_extras_2e_preheader_2e_lr_2e_ph_label: {
  mul_z_load281_Nxy_load282_broadcast_2e_elt0_ = ((uint32_t )(((uint32_t )counter_2e_0456_) * ((uint32_t )mul_Nx_load_Ny_load_)));
  add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0222_ = ((uint32_t )(((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_) + ((uint32_t )Nx_)));
  add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0232_ = ((uint32_t )(((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_) - ((uint32_t )Nx_)));
  add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0242_ = ((uint32_t )(((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_) + ((uint32_t )mul_Nx_load_Ny_load_)));
  add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0252_ = ((uint32_t )(((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_) - ((uint32_t )mul_Nx_load_Ny_load_)));
  tmp440_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter_2e_0456_) + ((uint32_t )2u))))) * ((uint32_t )mul_Nx_load_Ny_load_)));
  tmp442_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter_2e_0456_) + ((uint32_t )4294967294u))))) * ((uint32_t )mul_Nx_load_Ny_load_)));
  tmp448_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter_2e_0456_) + ((uint32_t )3u))))) * ((uint32_t )mul_Nx_load_Ny_load_)));
  tmp450_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter_2e_0456_) + ((uint32_t )4294967293u))))) * ((uint32_t )mul_Nx_load_Ny_load_)));
  if ((((int32_t )aligned_end31_) > ((int32_t )x0_))) {
    counter25_2e_1454_2e_us___PHI = y0_;   /* for PHI node */
    goto foreach_full_body_2e_lr_2e_ph_2e_us_label;
  } else {
    indvars_2e_iv___PHI = tmp__1_;   /* for PHI node */
    goto partial_inner_all_outer_label;
  }

}
  do {     /* Syntactic loop 'partial_inner_all_outer' to make GCC happy */
partial_inner_all_outer_label: {
  indvars_2e_iv_ = indvars_2e_iv___PHI;
  if ((((int32_t )x0_) < ((int32_t )x1_))) {
    goto partial_inner_only_label;
  } else {
    goto foreach_reset27_label;
  }

}
partial_inner_only_label: {
  x0_smear_ = __smear_i32<__vec16_i32>(x0_);
  cmp275_ = __signed_less_than_i32((__add(x0_smear_, __load<64>((const __vec16_i32  *)(VectorConstant1)))), x1_smear_);
  tmp__4_ = ((uint32_t )indvars_2e_iv_);
  mul_y_load283_Nx_load284_broadcast_2e_elt0_ = ((uint32_t )(((uint32_t )tmp__4_) * ((uint32_t )Nx_)));
  coef_load287_offset_load_ = *coef_;
  coef_load287_offset_load_smear_ = __smear_float<__vec16_f>(coef_load287_offset_load_);
  scaled_offsets197_2e_elt0_ = (((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_) + ((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_))))) + ((uint32_t )x0_)))) << 2u;
  tmp__5_ = ((int64_t )(int32_t )scaled_offsets197_2e_elt0_);
  ptr199_ = (&Ain_load293_ptr2int_2void_[((int64_t )tmp__5_)]);
  ptr199_masked_load_ = __masked_load_float(ptr199_, cmp275_);
  coef_load298_offset_load_ = *coef_load298_offset_;
  coef_load298_offset_load_smear_ = __smear_float<__vec16_f>(coef_load298_offset_load_);
  ptr208_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )4u)))))))])), cmp275_);
  ptr218_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )4294967292u)))))))])), cmp275_);
  ptr228_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0222_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_))))) + ((uint32_t )x0_)))) << 2u))))])), cmp275_);
  ptr238_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0232_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_))))) + ((uint32_t )x0_)))) << 2u))))])), cmp275_);
  ptr248_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0242_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_))))) + ((uint32_t )x0_)))) << 2u))))])), cmp275_);
  ptr258_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0252_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_))))) + ((uint32_t )x0_)))) << 2u))))])), cmp275_);
  coef_load349_offset_load_ = *coef_load349_offset_;
  coef_load349_offset_load_smear_ = __smear_float<__vec16_f>(coef_load349_offset_load_);
  ptr268_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )8u)))))))])), cmp275_);
  ptr278_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )4294967288u)))))))])), cmp275_);
  add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_ = ((uint32_t )(((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_) + ((uint32_t )x0_)));
  ptr288_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )tmp__4_) + ((uint32_t )2u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_);
  ptr298_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )tmp__4_) + ((uint32_t )4294967294u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_);
  add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_ = ((uint32_t )(((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_) + ((uint32_t )x0_)));
  ptr308_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_) + ((uint32_t )tmp440_)))) << 2u))))])), cmp275_);
  ptr318_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_) + ((uint32_t )tmp442_)))) << 2u))))])), cmp275_);
  coef_load400_offset_load_ = *coef_load400_offset_;
  coef_load400_offset_load_smear_ = __smear_float<__vec16_f>(coef_load400_offset_load_);
  ptr328_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )12u)))))))])), cmp275_);
  ptr338_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_) + ((uint32_t )4294967284u)))))))])), cmp275_);
  ptr348_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )tmp__4_) + ((uint32_t )3u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_);
  ptr358_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )tmp__4_) + ((uint32_t )4294967293u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_);
  ptr368_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_) + ((uint32_t )tmp448_)))) << 2u))))])), cmp275_);
  ptr378_masked_load_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_) + ((uint32_t )tmp450_)))) << 2u))))])), cmp275_);
  ptr388_masked_load_ = __masked_load_float(ptr199_, cmp275_);
  ptr398_ = (&Aout_load466_ptr2int_2void_[((int64_t )tmp__5_)]);
  ptr398_masked_load_ = __masked_load_float(ptr398_, cmp275_);
  ptr408_masked_load_ = __masked_load_float(((&vsq_load472_ptr2int_2void_[((int64_t )tmp__5_)])), cmp275_);
  __masked_store_float((((__vec16_f (*))ptr398_)), (__add((__sub((__mul(ptr388_masked_load_, __smear_float<__vec16_f>(0x1p+1))), ptr398_masked_load_)), (__mul(ptr408_masked_load_, (__add((__add((__add((__mul(ptr199_masked_load_, coef_load287_offset_load_smear_)), (__mul(coef_load298_offset_load_smear_, (__add((__add((__add((__add((__add(ptr208_masked_load_, ptr218_masked_load_)), ptr228_masked_load_)), ptr238_masked_load_)), ptr248_masked_load_)), ptr258_masked_load_)))))), (__mul(coef_load349_offset_load_smear_, (__add((__add((__add((__add((__add(ptr268_masked_load_, ptr278_masked_load_)), ptr288_masked_load_)), ptr298_masked_load_)), ptr308_masked_load_)), ptr318_masked_load_)))))), (__mul(coef_load400_offset_load_smear_, (__add((__add((__add((__add((__add(ptr328_masked_load_, ptr338_masked_load_)), ptr348_masked_load_)), ptr358_masked_load_)), ptr368_masked_load_)), ptr378_masked_load_)))))))))), cmp275_);
  goto foreach_reset27_label;

}
foreach_reset27_label: {
  indvars_2e_iv_2e_next_ = ((uint64_t )(((uint64_t )indvars_2e_iv_) + ((uint64_t )1ull)));
  if ((((int32_t )(((uint32_t )indvars_2e_iv_2e_next_))) < ((int32_t )y1_))) {
    indvars_2e_iv___PHI = indvars_2e_iv_2e_next_;   /* for PHI node */
    goto partial_inner_all_outer_label;
  } else {
    goto foreach_reset19_label;
  }

}
  } while (1); /* end of syntactic loop 'partial_inner_all_outer' */
  do {     /* Syntactic loop 'foreach_full_body.lr.ph.us' to make GCC happy */
foreach_full_body_2e_lr_2e_ph_2e_us_label: {
  counter25_2e_1454_2e_us_ = counter25_2e_1454_2e_us___PHI;
  mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_ = ((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) * ((uint32_t )Nx_)));
  add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_ = ((uint32_t )(((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_) + ((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_)));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt024_2e_us_ = ((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0222_) + ((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_)));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt033_2e_us_ = ((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0232_) + ((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_)));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt042_2e_us_ = ((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0242_) + ((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_)));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt051_2e_us_ = ((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0252_) + ((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_)));
  tmp420_2e_us_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )2u))))) * ((uint32_t )Nx_)));
  tmp422_2e_us_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )4294967294u))))) * ((uint32_t )Nx_)));
  tmp428_2e_us_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )3u))))) * ((uint32_t )Nx_)));
  tmp430_2e_us_ = ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )4294967293u))))) * ((uint32_t )Nx_)));
  counter32_2e_4452_2e_us___PHI = x0_;   /* for PHI node */
  goto foreach_full_body_2e_us_label;

}
  do {     /* Syntactic loop 'foreach_full_body.us' to make GCC happy */
foreach_full_body_2e_us_label: {
  counter32_2e_4452_2e_us_ = counter32_2e_4452_2e_us___PHI;
  coef_load_offset_load_2e_us_ = *coef_;
  coef_load_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load_offset_load_2e_us_);
  scaled_offsets_2e_elt0_2e_us_ = (((uint32_t )(((uint32_t )add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_) + ((uint32_t )counter32_2e_4452_2e_us_)))) << 2u;
  tmp__3_ = ((int64_t )(int32_t )scaled_offsets_2e_elt0_2e_us_);
  ptr_cast_for_load_2e_us_ = ((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )tmp__3_)])));
  ptr_masked_load1_2e_us_ = __load<4>(ptr_cast_for_load_2e_us_);
  coef_load82_offset_load_2e_us_ = *coef_load298_offset_;
  coef_load82_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load82_offset_load_2e_us_);
  ptr7_masked_load9_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )4u)))))))])))));
  ptr16_masked_load18_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )4294967292u)))))))])))));
  ptr25_masked_load27_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt024_2e_us_) + ((uint32_t )counter32_2e_4452_2e_us_)))) << 2u))))])))));
  ptr34_masked_load36_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt033_2e_us_) + ((uint32_t )counter32_2e_4452_2e_us_)))) << 2u))))])))));
  ptr43_masked_load45_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt042_2e_us_) + ((uint32_t )counter32_2e_4452_2e_us_)))) << 2u))))])))));
  ptr52_masked_load54_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt051_2e_us_) + ((uint32_t )counter32_2e_4452_2e_us_)))) << 2u))))])))));
  coef_load133_offset_load_2e_us_ = *coef_load349_offset_;
  coef_load133_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load133_offset_load_2e_us_);
  ptr61_masked_load63_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )8u)))))))])))));
  ptr70_masked_load72_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )4294967288u)))))))])))));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_ = ((uint32_t )(((uint32_t )counter32_2e_4452_2e_us_) + ((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_)));
  ptr79_masked_load81_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_) + ((uint32_t )tmp420_2e_us_)))) << 2u))))])))));
  ptr88_masked_load90_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_) + ((uint32_t )tmp422_2e_us_)))) << 2u))))])))));
  add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_ = ((uint32_t )(((uint32_t )counter32_2e_4452_2e_us_) + ((uint32_t )mul_y_load_Nx_load72_broadcast_2e_elt0_2e_us_)));
  ptr97_masked_load99_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_) + ((uint32_t )tmp440_)))) << 2u))))])))));
  ptr106_masked_load108_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_) + ((uint32_t )tmp442_)))) << 2u))))])))));
  coef_load184_offset_load_2e_us_ = *coef_load400_offset_;
  coef_load184_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load184_offset_load_2e_us_);
  ptr115_masked_load117_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )12u)))))))])))));
  ptr124_masked_load126_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets_2e_elt0_2e_us_) + ((uint32_t )4294967284u)))))))])))));
  ptr133_masked_load135_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_) + ((uint32_t )tmp428_2e_us_)))) << 2u))))])))));
  ptr142_masked_load144_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt078_2e_us_) + ((uint32_t )tmp430_2e_us_)))) << 2u))))])))));
  ptr151_masked_load153_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_) + ((uint32_t )tmp448_)))) << 2u))))])))));
  ptr160_masked_load162_2e_us_ = __load<4>((((__vec16_f (*))((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load_Nxy_load_broadcast_mul_y_load_Nx_load72_broadcast_x_load73_2e_elt096_2e_us_) + ((uint32_t )tmp450_)))) << 2u))))])))));
  ptr169_masked_load171_2e_us_ = __load<4>(ptr_cast_for_load_2e_us_);
  ptr_cast_for_load179_2e_us_ = ((__vec16_f (*))((&Aout_load466_ptr2int_2void_[((int64_t )tmp__3_)])));
  ptr178_masked_load180_2e_us_ = __load<4>(ptr_cast_for_load179_2e_us_);
  ptr187_masked_load189_2e_us_ = __load<4>((((__vec16_f (*))((&vsq_load472_ptr2int_2void_[((int64_t )tmp__3_)])))));
  __store<4>(ptr_cast_for_load179_2e_us_, (__add((__sub((__mul(ptr169_masked_load171_2e_us_, __smear_float<__vec16_f>(0x1p+1))), ptr178_masked_load180_2e_us_)), (__mul(ptr187_masked_load189_2e_us_, (__add((__add((__add((__mul(ptr_masked_load1_2e_us_, coef_load_offset_load_2e_us_smear_)), (__mul(coef_load82_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr7_masked_load9_2e_us_, ptr16_masked_load18_2e_us_)), ptr25_masked_load27_2e_us_)), ptr34_masked_load36_2e_us_)), ptr43_masked_load45_2e_us_)), ptr52_masked_load54_2e_us_)))))), (__mul(coef_load133_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr61_masked_load63_2e_us_, ptr70_masked_load72_2e_us_)), ptr79_masked_load81_2e_us_)), ptr88_masked_load90_2e_us_)), ptr97_masked_load99_2e_us_)), ptr106_masked_load108_2e_us_)))))), (__mul(coef_load184_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr115_masked_load117_2e_us_, ptr124_masked_load126_2e_us_)), ptr133_masked_load135_2e_us_)), ptr142_masked_load144_2e_us_)), ptr151_masked_load153_2e_us_)), ptr160_masked_load162_2e_us_)))))))))));
  new_counter267_2e_us_ = ((uint32_t )(((uint32_t )counter32_2e_4452_2e_us_) + ((uint32_t )16u)));
  if ((((int32_t )new_counter267_2e_us_) < ((int32_t )aligned_end31_))) {
    counter32_2e_4452_2e_us___PHI = new_counter267_2e_us_;   /* for PHI node */
    goto foreach_full_body_2e_us_label;
  } else {
    goto partial_inner_all_outer_2e_us_label;
  }

}
  } while (1); /* end of syntactic loop 'foreach_full_body.us' */
partial_inner_all_outer_2e_us_label: {
  if ((((int32_t )new_counter267_2e_us_) < ((int32_t )x1_))) {
    goto partial_inner_only_2e_us_label;
  } else {
    goto foreach_reset27_2e_us_label;
  }

}
partial_inner_only_2e_us_label: {
  new_counter267_2e_us_smear_ = __smear_i32<__vec16_i32>(new_counter267_2e_us_);
  cmp275_2e_us_ = __signed_less_than_i32((__add(new_counter267_2e_us_smear_, __load<64>((const __vec16_i32  *)(VectorConstant1)))), x1_smear_);
  mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_ = ((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) * ((uint32_t )Nx_)));
  coef_load287_offset_load_2e_us_ = *coef_;
  coef_load287_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load287_offset_load_2e_us_);
  scaled_offsets197_2e_elt0_2e_us_ = (((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_) + ((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_))))) + ((uint32_t )new_counter267_2e_us_)))) << 2u;
  tmp__2_ = ((int64_t )(int32_t )scaled_offsets197_2e_elt0_2e_us_);
  ptr199_2e_us_ = (&Ain_load293_ptr2int_2void_[((int64_t )tmp__2_)]);
  ptr199_masked_load_2e_us_ = __masked_load_float(ptr199_2e_us_, cmp275_2e_us_);
  coef_load298_offset_load_2e_us_ = *coef_load298_offset_;
  coef_load298_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load298_offset_load_2e_us_);
  ptr208_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )4u)))))))])), cmp275_2e_us_);
  ptr218_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )4294967292u)))))))])), cmp275_2e_us_);
  ptr228_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0222_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_))))) + ((uint32_t )new_counter267_2e_us_)))) << 2u))))])), cmp275_2e_us_);
  ptr238_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0232_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_))))) + ((uint32_t )new_counter267_2e_us_)))) << 2u))))])), cmp275_2e_us_);
  ptr248_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0242_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_))))) + ((uint32_t )new_counter267_2e_us_)))) << 2u))))])), cmp275_2e_us_);
  ptr258_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_2e_elt0252_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_))))) + ((uint32_t )new_counter267_2e_us_)))) << 2u))))])), cmp275_2e_us_);
  coef_load349_offset_load_2e_us_ = *coef_load349_offset_;
  coef_load349_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load349_offset_load_2e_us_);
  ptr268_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )8u)))))))])), cmp275_2e_us_);
  ptr278_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )4294967288u)))))))])), cmp275_2e_us_);
  add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_ = ((uint32_t )(((uint32_t )new_counter267_2e_us_) + ((uint32_t )mul_z_load281_Nxy_load282_broadcast_2e_elt0_)));
  ptr288_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )2u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_2e_us_);
  ptr298_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )4294967294u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_2e_us_);
  add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_ = ((uint32_t )(((uint32_t )new_counter267_2e_us_) + ((uint32_t )mul_y_load283_Nx_load284_broadcast_2e_elt0_2e_us_)));
  ptr308_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_) + ((uint32_t )tmp440_)))) << 2u))))])), cmp275_2e_us_);
  ptr318_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_) + ((uint32_t )tmp442_)))) << 2u))))])), cmp275_2e_us_);
  coef_load400_offset_load_2e_us_ = *coef_load400_offset_;
  coef_load400_offset_load_2e_us_smear_ = __smear_float<__vec16_f>(coef_load400_offset_load_2e_us_);
  ptr328_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )12u)))))))])), cmp275_2e_us_);
  ptr338_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )(((uint32_t )(((uint32_t )scaled_offsets197_2e_elt0_2e_us_) + ((uint32_t )4294967284u)))))))])), cmp275_2e_us_);
  ptr348_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )3u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_2e_us_);
  ptr358_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0287_2e_us_) + ((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )4294967293u))))) * ((uint32_t )Nx_)))))))) << 2u))))])), cmp275_2e_us_);
  ptr368_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_) + ((uint32_t )tmp448_)))) << 2u))))])), cmp275_2e_us_);
  ptr378_masked_load_2e_us_ = __masked_load_float(((&Ain_load293_ptr2int_2void_[((int64_t )(((int64_t )(int32_t )((((uint32_t )(((uint32_t )add_add_mul_z_load281_Nxy_load282_broadcast_mul_y_load283_Nx_load284_broadcast_x_load285_2e_elt0307_2e_us_) + ((uint32_t )tmp450_)))) << 2u))))])), cmp275_2e_us_);
  ptr388_masked_load_2e_us_ = __masked_load_float(ptr199_2e_us_, cmp275_2e_us_);
  ptr398_2e_us_ = (&Aout_load466_ptr2int_2void_[((int64_t )tmp__2_)]);
  ptr398_masked_load_2e_us_ = __masked_load_float(ptr398_2e_us_, cmp275_2e_us_);
  ptr408_masked_load_2e_us_ = __masked_load_float(((&vsq_load472_ptr2int_2void_[((int64_t )tmp__2_)])), cmp275_2e_us_);
  __masked_store_float((((__vec16_f (*))ptr398_2e_us_)), (__add((__sub((__mul(ptr388_masked_load_2e_us_, __smear_float<__vec16_f>(0x1p+1))), ptr398_masked_load_2e_us_)), (__mul(ptr408_masked_load_2e_us_, (__add((__add((__add((__mul(ptr199_masked_load_2e_us_, coef_load287_offset_load_2e_us_smear_)), (__mul(coef_load298_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr208_masked_load_2e_us_, ptr218_masked_load_2e_us_)), ptr228_masked_load_2e_us_)), ptr238_masked_load_2e_us_)), ptr248_masked_load_2e_us_)), ptr258_masked_load_2e_us_)))))), (__mul(coef_load349_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr268_masked_load_2e_us_, ptr278_masked_load_2e_us_)), ptr288_masked_load_2e_us_)), ptr298_masked_load_2e_us_)), ptr308_masked_load_2e_us_)), ptr318_masked_load_2e_us_)))))), (__mul(coef_load400_offset_load_2e_us_smear_, (__add((__add((__add((__add((__add(ptr328_masked_load_2e_us_, ptr338_masked_load_2e_us_)), ptr348_masked_load_2e_us_)), ptr358_masked_load_2e_us_)), ptr368_masked_load_2e_us_)), ptr378_masked_load_2e_us_)))))))))), cmp275_2e_us_);
  goto foreach_reset27_2e_us_label;

}
foreach_reset27_2e_us_label: {
  new_counter35_2e_us_ = ((uint32_t )(((uint32_t )counter25_2e_1454_2e_us_) + ((uint32_t )1u)));
  if ((new_counter35_2e_us_ == y1_)) {
    goto foreach_reset19_label;
  } else {
    counter25_2e_1454_2e_us___PHI = new_counter35_2e_us_;   /* for PHI node */
    goto foreach_full_body_2e_lr_2e_ph_2e_us_label;
  }

}
  } while (1); /* end of syntactic loop 'foreach_full_body.lr.ph.us' */
foreach_reset19_label: {
  new_counter_ = ((uint32_t )(((uint32_t )counter_2e_0456_) + ((uint32_t )1u)));
  if ((new_counter_ == z1_)) {
    goto foreach_reset_label;
  } else {
    counter_2e_0456___PHI = new_counter_;   /* for PHI node */
    goto foreach_test21_2e_preheader_label;
  }

}
  } while (1); /* end of syntactic loop 'foreach_test21.preheader' */
}



static void stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(l_unnamed_0 *tmp__6_, uint32_t tmp__7_, uint32_t tmp__8_, uint32_t tmp__9_, uint32_t tmp__10_) {
  uint32_t x02_;
  uint32_t x14_;
  uint32_t y06_;
  uint32_t y18_;
  uint32_t z010_;
  uint32_t Nx12_;
  uint32_t Ny14_;
  float *coef18_;
  float *vsq20_;
  float *Ain22_;
  float *Aout24_;

  x02_ = *((&tmp__6_->field0));
  x14_ = *((&tmp__6_->field1));
  y06_ = *((&tmp__6_->field2));
  y18_ = *((&tmp__6_->field3));
  z010_ = *((&tmp__6_->field4));
  Nx12_ = *((&tmp__6_->field5));
  Ny14_ = *((&tmp__6_->field6));
  coef18_ = *((&tmp__6_->field8));
  vsq20_ = *((&tmp__6_->field9));
  Ain22_ = *((&tmp__6_->field10));
  Aout24_ = *((&tmp__6_->field11));
   /*tail*/ stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(x02_, x14_, y06_, y18_, (((uint32_t )(((uint32_t )z010_) + ((uint32_t )tmp__9_)))), (((uint32_t )(((uint32_t )(((uint32_t )(((uint32_t )tmp__9_) + ((uint32_t )1u))))) + ((uint32_t )z010_)))), Nx12_, Ny14_, coef18_, vsq20_, Ain22_, Aout24_);
  return;
}



void loop_stencil_ispc_tasks___uniuniuniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_un_3C_unf_3E_(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_, __vec16_i1 __mask_) {
  uint8_t *launch_group_handle_;    /* Address-exposed local */
  uint32_t sub_z1_load_z0_load21_;
  uint32_t storemerge75_;
  uint32_t storemerge75___PHI;
  uint8_t *args_ptr_;
  float **tmp__11_;
  uint8_t *launch_group_handle_load70_2e_pre_;
  uint8_t *launch_group_handle_load_;
  uint32_t t_load69_plus1_;

  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  if ((((int32_t )t0_) < ((int32_t )t1_))) {
    goto for_loop_2e_lr_2e_ph_label;
  } else {
    goto post_sync73_label;
  }

for_loop_2e_lr_2e_ph_label: {
  sub_z1_load_z0_load21_ = ((uint32_t )(((uint32_t )z1_) - ((uint32_t )z0_)));
  storemerge75___PHI = t0_;   /* for PHI node */
  goto for_loop_label;

}
  do {     /* Syntactic loop 'for_loop' to make GCC happy */
for_loop_label: {
  storemerge75_ = storemerge75___PHI;
  args_ptr_ = ISPCAlloc((&launch_group_handle_), 72ull, 64u);
  *(((uint32_t *)args_ptr_)) = x0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )4ull)])))) = x1_;
  *(((uint32_t *)((&args_ptr_[((int64_t )8ull)])))) = y0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )12ull)])))) = y1_;
  *(((uint32_t *)((&args_ptr_[((int64_t )16ull)])))) = z0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )20ull)])))) = Nx_;
  *(((uint32_t *)((&args_ptr_[((int64_t )24ull)])))) = Ny_;
  *(((uint32_t *)((&args_ptr_[((int64_t )28ull)])))) = Nz_;
  *(((float **)((&args_ptr_[((int64_t )32ull)])))) = coef_;
  *(((float **)((&args_ptr_[((int64_t )40ull)])))) = vsq_;
  tmp__11_ = ((float **)((&args_ptr_[((int64_t )48ull)])));
  if (((storemerge75_ & 1u) == 0u)) {
    goto if_then_label;
  } else {
    goto if_else_label;
  }

}
if_else_label: {
  *tmp__11_ = Aodd_;
  *(((float **)((&args_ptr_[((int64_t )56ull)])))) = Aeven_;
  __store<2>((((__vec16_i1 (*))((&args_ptr_[((int64_t )64ull)])))), __mask_);
  ISPCLaunch((&launch_group_handle_), ((uint8_t *)stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_), args_ptr_, sub_z1_load_z0_load21_);
  goto if_exit_label;

}
if_then_label: {
  *tmp__11_ = Aeven_;
  *(((float **)((&args_ptr_[((int64_t )56ull)])))) = Aodd_;
  __store<2>((((__vec16_i1 (*))((&args_ptr_[((int64_t )64ull)])))), __mask_);
  ISPCLaunch((&launch_group_handle_), ((uint8_t *)stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_), args_ptr_, sub_z1_load_z0_load21_);
  goto if_exit_label;

}
if_exit_label: {
  launch_group_handle_load_ = *(&launch_group_handle_);
  if ((launch_group_handle_load_ == ((uint8_t *)/*NULL*/0))) {
    goto post_sync_label;
  } else {
    goto call_sync_label;
  }

}
call_sync_label: {
  ISPCSync(launch_group_handle_load_);
  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  goto post_sync_label;

}
post_sync_label: {
  t_load69_plus1_ = ((uint32_t )(((uint32_t )storemerge75_) + ((uint32_t )1u)));
  if ((t_load69_plus1_ == t1_)) {
    goto for_exit_label;
  } else {
    storemerge75___PHI = t_load69_plus1_;   /* for PHI node */
    goto for_loop_label;
  }

}
  } while (1); /* end of syntactic loop 'for_loop' */
for_exit_label: {
  launch_group_handle_load70_2e_pre_ = *(&launch_group_handle_);
  if ((launch_group_handle_load70_2e_pre_ == ((uint8_t *)/*NULL*/0))) {
    goto post_sync73_label;
  } else {
    goto call_sync72_label;
  }

}
call_sync72_label: {
  ISPCSync(launch_group_handle_load70_2e_pre_);
  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  goto post_sync73_label;

}
post_sync73_label: {
  return;
}
}



void loop_stencil_ispc___uniuniuniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_un_3C_unf_3E_(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_, __vec16_i1 __mask_) {
  uint32_t storemerge40_;
  uint32_t storemerge40___PHI;
  uint32_t t_load38_plus1_;

  if ((((int32_t )t0_) < ((int32_t )t1_))) {
    storemerge40___PHI = t0_;   /* for PHI node */
    goto for_loop_label;
  } else {
    goto for_exit_label;
  }

  do {     /* Syntactic loop 'for_loop' to make GCC happy */
for_loop_label: {
  storemerge40_ = storemerge40___PHI;
  if (((storemerge40_ & 1u) == 0u)) {
    goto if_then_label;
  } else {
    goto if_else_label;
  }

}
if_else_label: {
   /*tail*/ stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(x0_, x1_, y0_, y1_, z0_, z1_, Nx_, Ny_, coef_, vsq_, Aodd_, Aeven_);
  goto if_exit_label;

}
if_then_label: {
   /*tail*/ stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(x0_, x1_, y0_, y1_, z0_, z1_, Nx_, Ny_, coef_, vsq_, Aeven_, Aodd_);
  goto if_exit_label;

}
if_exit_label: {
  t_load38_plus1_ = ((uint32_t )(((uint32_t )storemerge40_) + ((uint32_t )1u)));
  if ((t_load38_plus1_ == t1_)) {
    goto for_exit_label;
  } else {
    storemerge40___PHI = t_load38_plus1_;   /* for PHI node */
    goto for_loop_label;
  }

}
  } while (1); /* end of syntactic loop 'for_loop' */
for_exit_label: {
  return;
}
}



void loop_stencil_ispc_tasks(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_) {
  uint8_t *launch_group_handle_;    /* Address-exposed local */
  uint32_t sub_z1_load_z0_load21_;
  uint32_t storemerge75_;
  uint32_t storemerge75___PHI;
  uint8_t *args_ptr_;
  float **tmp__12_;
  uint8_t *launch_group_handle_load70_2e_pre_;
  uint8_t *launch_group_handle_load_;
  uint32_t t_load69_plus1_;

  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  if ((((int32_t )t0_) < ((int32_t )t1_))) {
    goto for_loop_2e_lr_2e_ph_label;
  } else {
    goto post_sync73_label;
  }

for_loop_2e_lr_2e_ph_label: {
  sub_z1_load_z0_load21_ = ((uint32_t )(((uint32_t )z1_) - ((uint32_t )z0_)));
  storemerge75___PHI = t0_;   /* for PHI node */
  goto for_loop_label;

}
  do {     /* Syntactic loop 'for_loop' to make GCC happy */
for_loop_label: {
  storemerge75_ = storemerge75___PHI;
  args_ptr_ = ISPCAlloc((&launch_group_handle_), 72ull, 64u);
  *(((uint32_t *)args_ptr_)) = x0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )4ull)])))) = x1_;
  *(((uint32_t *)((&args_ptr_[((int64_t )8ull)])))) = y0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )12ull)])))) = y1_;
  *(((uint32_t *)((&args_ptr_[((int64_t )16ull)])))) = z0_;
  *(((uint32_t *)((&args_ptr_[((int64_t )20ull)])))) = Nx_;
  *(((uint32_t *)((&args_ptr_[((int64_t )24ull)])))) = Ny_;
  *(((uint32_t *)((&args_ptr_[((int64_t )28ull)])))) = Nz_;
  *(((float **)((&args_ptr_[((int64_t )32ull)])))) = coef_;
  *(((float **)((&args_ptr_[((int64_t )40ull)])))) = vsq_;
  tmp__12_ = ((float **)((&args_ptr_[((int64_t )48ull)])));
  if (((storemerge75_ & 1u) == 0u)) {
    goto if_then_label;
  } else {
    goto if_else_label;
  }

}
if_else_label: {
  *tmp__12_ = Aodd_;
  *(((float **)((&args_ptr_[((int64_t )56ull)])))) = Aeven_;
  __store<2>((((__vec16_i1 (*))((&args_ptr_[((int64_t )64ull)])))), __smear_i1<__vec16_i1>(1));
  ISPCLaunch((&launch_group_handle_), ((uint8_t *)stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_), args_ptr_, sub_z1_load_z0_load21_);
  goto if_exit_label;

}
if_then_label: {
  *tmp__12_ = Aeven_;
  *(((float **)((&args_ptr_[((int64_t )56ull)])))) = Aodd_;
  __store<2>((((__vec16_i1 (*))((&args_ptr_[((int64_t )64ull)])))), __smear_i1<__vec16_i1>(1));
  ISPCLaunch((&launch_group_handle_), ((uint8_t *)stencil_step_task___uniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_), args_ptr_, sub_z1_load_z0_load21_);
  goto if_exit_label;

}
if_exit_label: {
  launch_group_handle_load_ = *(&launch_group_handle_);
  if ((launch_group_handle_load_ == ((uint8_t *)/*NULL*/0))) {
    goto post_sync_label;
  } else {
    goto call_sync_label;
  }

}
call_sync_label: {
  ISPCSync(launch_group_handle_load_);
  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  goto post_sync_label;

}
post_sync_label: {
  t_load69_plus1_ = ((uint32_t )(((uint32_t )storemerge75_) + ((uint32_t )1u)));
  if ((t_load69_plus1_ == t1_)) {
    goto for_exit_label;
  } else {
    storemerge75___PHI = t_load69_plus1_;   /* for PHI node */
    goto for_loop_label;
  }

}
  } while (1); /* end of syntactic loop 'for_loop' */
for_exit_label: {
  launch_group_handle_load70_2e_pre_ = *(&launch_group_handle_);
  if ((launch_group_handle_load70_2e_pre_ == ((uint8_t *)/*NULL*/0))) {
    goto post_sync73_label;
  } else {
    goto call_sync72_label;
  }

}
call_sync72_label: {
  ISPCSync(launch_group_handle_load70_2e_pre_);
  *(&launch_group_handle_) = ((uint8_t *)/*NULL*/0);
  goto post_sync73_label;

}
post_sync73_label: {
  return;
}
}



void loop_stencil_ispc(uint32_t t0_, uint32_t t1_, uint32_t x0_, uint32_t x1_, uint32_t y0_, uint32_t y1_, uint32_t z0_, uint32_t z1_, uint32_t Nx_, uint32_t Ny_, uint32_t Nz_, float *coef_, float *vsq_, float *Aeven_, float *Aodd_) {
  uint32_t storemerge40_;
  uint32_t storemerge40___PHI;
  uint32_t t_load38_plus1_;

  if ((((int32_t )t0_) < ((int32_t )t1_))) {
    storemerge40___PHI = t0_;   /* for PHI node */
    goto for_loop_label;
  } else {
    goto for_exit_label;
  }

  do {     /* Syntactic loop 'for_loop' to make GCC happy */
for_loop_label: {
  storemerge40_ = storemerge40___PHI;
  if (((storemerge40_ & 1u) == 0u)) {
    goto if_then_label;
  } else {
    goto if_else_label;
  }

}
if_else_label: {
   /*tail*/ stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(x0_, x1_, y0_, y1_, z0_, z1_, Nx_, Ny_, coef_, vsq_, Aodd_, Aeven_);
  goto if_exit_label;

}
if_then_label: {
   /*tail*/ stencil_step___uniuniuniuniuniuniuniuniuniun_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_Cunf_3E_un_3C_unf_3E_(x0_, x1_, y0_, y1_, z0_, z1_, Nx_, Ny_, coef_, vsq_, Aeven_, Aodd_);
  goto if_exit_label;

}
if_exit_label: {
  t_load38_plus1_ = ((uint32_t )(((uint32_t )storemerge40_) + ((uint32_t )1u)));
  if ((t_load38_plus1_ == t1_)) {
    goto for_exit_label;
  } else {
    storemerge40___PHI = t_load38_plus1_;   /* for PHI node */
    goto for_loop_label;
  }

}
  } while (1); /* end of syntactic loop 'for_loop' */
for_exit_label: {
  return;
}
}

