//
// options_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_OPTIONS_ISPC_H
#define ISPC_OPTIONS_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void binomial_put_ispc(float * Sa, float * Xa, float * Ta, float * ra, float * va, float * result, int32_t count);
    extern void binomial_put_ispc_tasks(float * Sa, float * Xa, float * Ta, float * ra, float * va, float * result, int32_t count);
    extern void black_scholes_ispc(float * Sa, float * Xa, float * Ta, float * ra, float * va, float * result, int32_t count);
    extern void black_scholes_ispc_tasks(float * Sa, float * Xa, float * Ta, float * ra, float * va, float * result, int32_t count);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_OPTIONS_ISPC_H
